apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  containers:
  # docker run -d --name nginx nginx
    - name: nginx
      image: nginx
    nodeSelector:
      disktype: ssd
  tolerations:
   - key: "hardware"
     operator: "Equal"
     value: "gpu"
     effect: "NoSchedule"
